### ISSUE TITLE
打开sln第一次生成时报错  LNK1104 无法打开文件“yolo_cpp_dll-d.lib”

### ISSUE THREAD

**Issue by Rackar** [jing-interactive/DancingGaga#1]
1>------ 已启动生成: 项目: DancingGaga, 配置: Debug x64 ------
1>PDollar.cpp
1>d:\wsvs\dancing\lightnet\modules\pdollar\pdollar.cpp(185): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\pdollar\pdollar.cpp(200): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\pdollar\pdollar.cpp(213): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
1>MiniTraceHelper.cpp
1>VideoHelper.cpp
1>lightnet.cpp
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(24): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(25): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(26): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(35): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(36): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(39): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(40): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(41): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(45): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(46): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(47): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(52): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(53): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(59): warning C4305: “return”: 从“double”到“float”截断
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(71): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(81): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(82): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(83): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\modules\darknet\src\activations.h(85): warning C4244: “return”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\src\lightnet.cpp(108): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\lightnet\src\lightnet.cpp(115): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\lightnet\src\lightnet.cpp(131): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>os_hal.cpp
1>main.cpp
1>cvui.h: compiling implementation because of CVUI_IMPLEMENTATION. See: https://dovyski.github.io/cvui/usage/
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(120): warning C4305: “初始化”: 从“double”到“float”截断
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(123): warning C4305: “初始化”: 从“double”到“float”截断
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(125): warning C4305: “初始化”: 从“double”到“float”截断
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(127): warning C4305: “初始化”: 从“double”到“float”截断
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(234): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(235): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\main.cpp(346): warning C4244: “参数”: 从“float”转换到“int”，可能丢失数据
1>poseParameters.cpp
1>post_process.cpp
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(32): warning C4267: “return”: 从“size_t”转换到“uint32_t”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(67): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(67): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(68): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(68): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(130): warning C4018: “<”: 有符号/无符号不匹配
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(211): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(211): warning C4244: “初始化”: 从“float”转换到“const int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(212): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(212): warning C4244: “初始化”: 从“float”转换到“const int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(259): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(259): warning C4244: “初始化”: 从“double”转换到“const float”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(344): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(344): warning C4244: “初始化”: 从“double”转换到“const float”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(480): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(500): warning C4244: “初始化”: 从“float”转换到“int”，可能丢失数据
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(506): warning C4244: “=”: 从“float”转换到“int”，可能丢失数据
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(159): warning C4244: “初始化”: 从“const double”转换到“float”，可能丢失数据
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(281): note: 参见对正在编译的函数 模板 实例化“std::_Tuple_val<_This>::_Tuple_val<const _Ty&>(_Other)”的引用
1>        with
1>        [
1>            _This=float,
1>            _Ty=double,
1>            _Other=const double &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(280): note: 参见对正在编译的函数 模板 实例化“std::_Tuple_val<_This>::_Tuple_val<const _Ty&>(_Other)”的引用
1>        with
1>        [
1>            _This=float,
1>            _Ty=double,
1>            _Other=const double &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(863): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<std::_Exact_args_t,const double&,const int&,const int&,0>(_Tag,_This2,const int &,const int &)”的引用
1>        with
1>        [
1>            _Tag=std::_Exact_args_t,
1>            _This2=const double &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(862): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<std::_Exact_args_t,const double&,const int&,const int&,0>(_Tag,_This2,const int &,const int &)”的引用
1>        with
1>        [
1>            _Tag=std::_Exact_args_t,
1>            _This2=const double &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(296): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<std::_Unpack_tuple_t,const std::tuple<double,int,int>&,0,1,2,0>(_Tag,_Tpl,std::integer_sequence<_Ty,0,1,2>)”的引用
1>        with
1>        [
1>            _Tag=std::_Unpack_tuple_t,
1>            _Tpl=const std::tuple<double,int,int> &,
1>            _Ty=size_t
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(294): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<std::_Unpack_tuple_t,const std::tuple<double,int,int>&,0,1,2,0>(_Tag,_Tpl,std::integer_sequence<_Ty,0,1,2>)”的引用
1>        with
1>        [
1>            _Tag=std::_Unpack_tuple_t,
1>            _Tpl=const std::tuple<double,int,int> &,
1>            _Ty=size_t
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(339): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<std::_Unpack_tuple_t,const std::tuple<double,int,int>&,0>(_Tag,_Tpl)”的引用
1>        with
1>        [
1>            _Tag=std::_Unpack_tuple_t,
1>            _Tpl=const std::tuple<double,int,int> &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\tuple(338): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<std::_Unpack_tuple_t,const std::tuple<double,int,int>&,0>(_Tag,_Tpl)”的引用
1>        with
1>        [
1>            _Tag=std::_Unpack_tuple_t,
1>            _Tpl=const std::tuple<double,int,int> &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\algorithm(3846): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<double,int,int,0,0>(const std::tuple<double,int,int> &)”的引用
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\algorithm(3844): note: 参见对正在编译的函数 模板 实例化“std::tuple<float,int,int>::tuple<double,int,int,0,0>(const std::tuple<double,int,int> &)”的引用
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\algorithm(3939): note: 参见对正在编译的函数 模板 实例化“std::pair<_RanIt,_RanIt> std::_Partition_by_median_guess_unchecked<_RanIt,_Pr>(_RanIt,_RanIt,_Pr)”的引用
1>        with
1>        [
1>            _RanIt=std::tuple<double,int,int> *,
1>            _Pr=std::greater<std::tuple<float,int,int>>
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\algorithm(3973): note: 参见对正在编译的函数 模板 实例化“void std::_Sort_unchecked<std::tuple<double,int,int>*,_Fn>(_RanIt,_RanIt,__int64,_Pr)”的引用
1>        with
1>        [
1>            _Fn=std::greater<std::tuple<float,int,int>>,
1>            _RanIt=std::tuple<double,int,int> *,
1>            _Pr=std::greater<std::tuple<float,int,int>>
1>        ]
1>d:\wsvs\dancing\dancinggaga-master\src\post_process.cpp(248): note: 参见对正在编译的函数 模板 实例化“void std::sort<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::greater<std::tuple<float,int,int>>>(const _RanIt,const _RanIt,_Pr)”的引用
1>        with
1>        [
1>            _Ty=std::tuple<double,int,int>,
1>            _RanIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<std::tuple<double,int,int>>>>,
1>            _Pr=std::greater<std::tuple<float,int,int>>
1>        ]
1>正在生成代码...
1>minitrace.c
1>LINK : fatal error LNK1104: 无法打开文件“yolo_cpp_dll-d.lib”
1>已完成生成项目“DancingGaga.vcxproj”的操作 - 失败。

**Comment by vinjn** [comment]
lightnet 编译了么？

**Comment by Rackar** [comment]
只执行到了build.bat 下面是执行过程

D:\wsVS\dancing\lightnet> .\build.bat

D:\wsVS\dancing\lightnet>REM =========================

D:\wsVS\dancing\lightnet>REM Build

D:\wsVS\dancing\lightnet>REM =========================

D:\wsVS\dancing\lightnet>msbuild darknet_vs\darknet.sln /p:Configuration=Release /p:Platform=x64 /v:minimal /m
'msbuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\wsVS\dancing\lightnet>REM msbuild darknet_vs\darknet.sln /p:Configuration=Release-CPU /p:Platform=x64 /v:minimal /m

D:\wsVS\dancing\lightnet>msbuild darknet_vs\yolo_cpp_dll.sln /p:Configuration=Release /p:Platform=x64 /v:minimal /m
'msbuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\wsVS\dancing\lightnet>msbuild darknet_vs\yolo_cpp_dll.sln /p:Configuration=Debug /p:Platform=x64 /v:minimal /m
'msbuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\wsVS\dancing\lightnet>REM msbuild darknet_vs\yolo_cpp_dll.sln /p:Configuration=Release-CPU /p:Platform=x64 /v:minimal /m

D:\wsVS\dancing\lightnet>msbuild modules\Yolo_mark\yolo_mark.sln /p:Configuration=Release /p:Platform=x64 /v:minimal /m
'msbuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\wsVS\dancing\lightnet>REM msbuild modules\yolo2_light\yolo_gpu.sln /p:Configuration=Release /p:Platform=x64 /v:minimal /m

D:\wsVS\dancing\lightnet>REM =========================

D:\wsVS\dancing\lightnet>REM Deploy to bin/

D:\wsVS\dancing\lightnet>REM =========================

D:\wsVS\dancing\lightnet>REM robocopy darknet_vs\bin\ bin\ *.exe

D:\wsVS\dancing\lightnet>REM robocopy darknet_vs\bin\ bin\ *.lib

D:\wsVS\dancing\lightnet>robocopy modules\darknet\build\darknet\x64\ bin\ pthreadVC2.dll

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:35
        源: D:\wsVS\dancing\lightnet\modules\darknet\build\darknet\x64\
      目标: D:\wsVS\dancing\lightnet\bin\

      文件: pthreadVC2.dll

      选项: /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           1    D:\wsVS\dancing\lightnet\modules\darknet\build\darknet\x64\

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0         0
       文件:         1         0         1         0         0         0
       字节:    81.0 k         0    81.0 k         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00
   结束时间: 2018年9月14日 12:02:35


D:\wsVS\dancing\lightnet>robocopy modules\darknet\cfg bin\cfg /E

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:36
        源: D:\wsVS\dancing\lightnet\modules\darknet\cfg\
      目标: D:\wsVS\dancing\lightnet\bin\cfg\

      文件: *.*

      选项: *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                          58    D:\wsVS\dancing\lightnet\modules\darknet\cfg\
                           8    D:\wsVS\dancing\lightnet\modules\darknet\cfg\yolov1\

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         2         0         2         0         0         0
       文件:        66         0        66         0         0         0
       字节:    1.00 m         0    1.00 m         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00
   结束时间: 2018年9月14日 12:02:36


D:\wsVS\dancing\lightnet>robocopy modules\darknet\data bin\data /E

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:36
        源: D:\wsVS\dancing\lightnet\modules\darknet\data\
      目标: D:\wsVS\dancing\lightnet\bin\data\

      文件: *.*

      选项: *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                          13    D:\wsVS\dancing\lightnet\modules\darknet\data\
                         761    D:\wsVS\dancing\lightnet\modules\darknet\data\labels\

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         2         0         2         0         0         0
       文件:       774         0       774         0         0         0
       字节:    2.06 m         0    2.06 m         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00
   结束时间: 2018年9月14日 12:02:36


D:\wsVS\dancing\lightnet>robocopy modules\Yolo_mark\x64\Release\ bin\ yolo_mark.exe

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:36
        源: D:\wsVS\dancing\lightnet\modules\Yolo_mark\x64\Release\
      目标: D:\wsVS\dancing\lightnet\bin\

      文件: yolo_mark.exe

      选项: /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           0    D:\wsVS\dancing\lightnet\modules\Yolo_mark\x64\Release\

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0         0
       文件:         0         0         0         0         0         0
       字节:         0         0         0         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00
   结束时间: 2018年9月14日 12:02:36


D:\wsVS\dancing\lightnet>REM robocopy modules\yolo2_light\bin\ bin\ yolo_gpu.exe

D:\wsVS\dancing\lightnet>robocopy D:\opencv\build\x64\vc14\bin\ bin\ *.dll

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:36
        源: D:\opencv\build\x64\vc14\bin\
      目标: D:\wsVS\dancing\lightnet\bin\

      文件: *.dll

      选项: /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           3    D:\opencv\build\x64\vc14\bin\
          *多余文件                82944        pthreadVC2.dll
100%        新文件                16.9 m        opencv_ffmpeg340_64.dll
100%        新文件                62.4 m        opencv_world340.dll
100%        新文件                99.3 m        opencv_world340d.dll

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0         0
       文件:         3         3         0         0         0         1
       字节:  178.74 m  178.74 m         0         0         0    81.0 k
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00


       速度:           1233101473 字节/秒。
       速度:            70558.632 MB/分钟。
   结束时间: 2018年9月14日 12:02:36


D:\wsVS\dancing\lightnet>REM =========================

D:\wsVS\dancing\lightnet>REM Deploy to scripts/

D:\wsVS\dancing\lightnet>REM =========================

D:\wsVS\dancing\lightnet>REM robocopy darknet_vs\bin\ bin\ *.dll

D:\wsVS\dancing\lightnet>robocopy bin\ scripts\ *.dll

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:36
        源: D:\wsVS\dancing\lightnet\bin\
      目标: D:\wsVS\dancing\lightnet\scripts\

      文件: *.dll

      选项: /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           4    D:\wsVS\dancing\lightnet\bin\
100%        新文件                16.9 m        opencv_ffmpeg340_64.dll
100%        新文件                62.4 m        opencv_world340.dll
100%        新文件                99.3 m        opencv_world340d.dll

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0         0
       文件:         4         3         1         0         0         0
       字节:  178.82 m  178.74 m    81.0 k         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00


       速度:           1511543741 字节/秒。
       速度:            86491.226 MB/分钟。
   结束时间: 2018年9月14日 12:02:36


D:\wsVS\dancing\lightnet>robocopy modules\darknet\ scripts\ darknet.py

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2018年9月14日 12:02:36
        源: D:\wsVS\dancing\lightnet\modules\darknet\
      目标: D:\wsVS\dancing\lightnet\scripts\

      文件: darknet.py

      选项: /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           1    D:\wsVS\dancing\lightnet\modules\darknet\

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0         0
       文件:         1         0         1         0         0         0
       字节:    15.8 k         0    15.8 k         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00
   结束时间: 2018年9月14日 12:02:36

**Comment by vinjn** [comment]
编译出错了

'msbuild' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by vinjn** [comment]
你可以人肉打开 `lightnet/darknet_vs/darknet.sln` 进行编译
