### ISSUE TITLE
how to use this openpose weight by the code of AlexeyAB's repo?

### ISSUE THREAD

**Issue by BackT0TheFuture** [jing-interactive/DancingGaga#4]
Hi,
thanks for your great work.
Is it possible to use this model by the code of [AlexeyAB's repo](https://github.com/AlexeyAB/darknet)?
I just wanna the keypoints. If it's yes, how to do?
thanks!

**Comment by vinjn** [comment]
I am using AlexeyAB's repo as submodules, so you should achieve the purpose directly.
Let me know if you have further questions.
